// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );007
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp4wHeixLVYCQ84hu0roHOmCdtDz2l480',
    appId: '1:173852853477:web:8178bb16078e2928f1400c',
    messagingSenderId: '173852853477',
    projectId: 'course-app-caa3e',
    authDomain: 'course-app-caa3e.firebaseapp.com',
    storageBucket: 'course-app-caa3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEHSBHA_Df1j_WoOsQ1Mk9PKi9O6q4g4',
    appId: '1:173852853477:android:ad5b3570620d7796f1400c',
    messagingSenderId: '173852853477',
    projectId: 'course-app-caa3e',
    storageBucket: 'course-app-caa3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKn6Y4efj21f0Rfwss0wFf6Xec-bcDuk',
    appId: '1:173852853477:ios:3fc1db402cd93c2df1400c',
    messagingSenderId: '173852853477',
    projectId: 'course-app-caa3e',
    storageBucket: 'course-app-caa3e.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );
}
